### ISSUE TITLE
isValidTime() does not support timezone

### ISSUE THREAD

**Issue by robross0606** [Bwca/iso-datestring-validator#13]
`isValidTime()` should support strings with timezone specification

**Comment by Bwca** [comment]
That's a good point, I'll see to that :+1:

**Comment by Bwca** [comment]
Updated the package, now isValidTime supports checking time with timezone specifications by passing a third param, which is boolean to enable timezone check, i.e.:

`isValidTime('14:45:15.000+00:00', ':', true)`
