### ISSUE TITLE
isValidISODateString fails when given only date

### ISSUE THREAD

**Issue by DanilchenkoNikolay** [Bwca/iso-datestring-validator#18]
When given valid date without time part ("2020-12-04") `isValidISODateString` fails with
`Uncaught TypeError: Cannot read property 'match' of undefined`
If date is not valid it works as expected: `"2020-13-01" -> false`

**Comment by Bwca** [comment]
Good issue, I'll look into it, thanks.

```isValidISODateString``` was not designed for validating dates without time though, there's ```isValidDate``` for that.

Could you please elaborate on your case? Are you always checking YYYY-MM-DD or it might also have time in some cases and you need a function that could validate both YYYY-MM-DD and YYYY-MM-DDThh:mm:ss?

**Comment by DanilchenkoNikolay** [comment]
I was looking for a function that decides if given string is a valid ISO with both date and time parts and rules out every other case including date only. So what I expect is `isValidISODateString("2020-12-04") -> false`. This is the intended behavior, right?

**Comment by Bwca** [comment]
I see, gonna fix the bug this week :)
