### ISSUE TITLE
The code accepts 00 as a valid day of the month

### ISSUE THREAD

**Issue by PhilipMorrisJones** [Bwca/iso-datestring-validator#30]
The code accepts 00 as a valid day of the month, so the zeroth of February 2022 is returned as a valid date

var iso = require("iso-datestring-validator");
console.log(iso.isValidDate('2022-02-00'));

**Comment by Bwca** [comment]
Gonna look into it, thanks for reporting :)

**Comment by Bwca** [comment]
Published 2.2.1, it should fix the issue :)
